export { prisma } from "./client.js";
export { Prisma } from "./generated/prisma/client.js";
export {
  AuditAction,
  CouponDiscountType,
  RefundStatus,
  ReservationStatus,
  OrderStatus,
  PaymentMethod,
  PaymentStatus,
  TableStatus,
  UserRole,
  UserStatus,
} from "./generated/prisma/client.js";
export type {
  AuditLog,
  Category,
  Coupon,
  Ingredient,
  LoyaltyAccount,
  LoyaltyPointEntry,
  Refund,
  Report,
  Reservation,
  Order,
  OrderItem,
  Payment,
  Product,
  ProductIngredient,
  PrismaClient,
  RefreshToken,
  Restaurant,
  RestaurantTable,
  User,
} from "./generated/prisma/client.js";
