export const AppErrorCode = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  AUTHENTICATION_REQUIRED: "AUTHENTICATION_REQUIRED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  ACCOUNT_NOT_ACTIVE: "ACCOUNT_NOT_ACTIVE",
  INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
  FORBIDDEN: "FORBIDDEN",

  USER_NOT_FOUND: "USER_NOT_FOUND",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  OWNER_ALREADY_EXISTS: "OWNER_ALREADY_EXISTS",

  CATEGORY_NOT_FOUND: "CATEGORY_NOT_FOUND",
  CATEGORY_NAME_ALREADY_EXISTS: "CATEGORY_NAME_ALREADY_EXISTS",
  CATEGORY_DISABLED: "CATEGORY_DISABLED",

  PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",
  PRODUCT_UNAVAILABLE: "PRODUCT_UNAVAILABLE",
  PRODUCT_NAME_ALREADY_EXISTS: "PRODUCT_NAME_ALREADY_EXISTS",

  TABLE_NOT_FOUND: "TABLE_NOT_FOUND",
  TABLE_UNAVAILABLE: "TABLE_UNAVAILABLE",
  TABLE_DISABLED: "TABLE_DISABLED",
  TABLE_HAS_ACTIVE_ORDERS: "TABLE_HAS_ACTIVE_ORDERS",
  TABLE_NUMBER_ALREADY_EXISTS: "TABLE_NUMBER_ALREADY_EXISTS",

  ORDER_NOT_FOUND: "ORDER_NOT_FOUND",
  ORDER_INVALID_STATUS: "ORDER_INVALID_STATUS",
  ORDER_NOT_PAID: "ORDER_NOT_PAID",
  ORDER_CANNOT_BE_COMPLETED: "ORDER_CANNOT_BE_COMPLETED",
  ORDER_ALREADY_COMPLETED: "ORDER_ALREADY_COMPLETED",
  ORDER_ALREADY_CANCELLED: "ORDER_ALREADY_CANCELLED",
  ORDER_CANNOT_BE_CANCELLED: "ORDER_CANNOT_BE_CANCELLED",

  PAYMENT_NOT_FOUND: "PAYMENT_NOT_FOUND",
  PAYMENT_ALREADY_EXISTS: "PAYMENT_ALREADY_EXISTS",
  PAYMENT_NOT_ALLOWED: "PAYMENT_NOT_ALLOWED",

  RESTAURANT_NOT_FOUND: "RESTAURANT_NOT_FOUND",

  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
} as const;

export type AppErrorCode =
  (typeof AppErrorCode)[keyof typeof AppErrorCode];
